### ISSUE TITLE
Automated build + deploy

### ISSUE THREAD

**Issue by mickaelistria** [AObuchow/lsp4xml-extensions-maven#1]
To improve feedback loop in m2e, it'd be great to have some automated builds available which would allow to easily include the latest build from master into m2e at build time (later, when we're ready, we'll probably stick to releases for more predictability/reproducibility but now, master is best).
To achieve so, best is probably to use GitHub Actions if possible.

**Comment by AObuchow** [comment]
Thank you for posting the first issue to this repository @mickaelistria!
🎉

To make sure I understand what you're suggesting, the automated build should not only verify that there are no build errors on this repo but also make sure there are no build errors when the maven extension jar is being included in m2e?

**Comment by mickaelistria** [comment]
> the automated build should not only verify that there are no build errors on this repo but also make sure there are no build errors when the maven extension jar is being included in m2e?

Not that much ;) Ideally, the build should 1. build (and report errors and failures) and 2. publish the snapshot to a stable URL so we can easily consume it in m2e.
For the m2e part, we'll try to have the .jar fetched from the last build automatically when we do a `mvn clean verify`.

**Comment by AObuchow** [comment]
Sounds good, thanks for detailing the requirements.

**Comment by AObuchow** [comment]
Didn't intend to close the issue... forgot the "fix" keyword does that.

**Comment by mickaelistria** [comment]
Cool, I see the build passed from master; however I don't see some URL where latest artifact is available. Do you think it's available somewhere, or maybe another build step is required for this to work?

**Comment by AObuchow** [comment]
> Cool, I see the build passed from master; however I don't see some URL where latest artifact is available. Do you think it's available somewhere, or maybe another build step is required for this to work?

I'm not sure I'm going to look further into the docs for GitHub actions. I'll figure it out :)

**Comment by mickaelistria** [comment]
As an alternative to publishing to a static URL, another possibility could be to use a Sonatype OSSHR account to publish the snapshot (with `mvn deploy`) to Maven Central, so it can be referenced easily.
I even think it should actually be preferred.

**Comment by AObuchow** [comment]
> As an alternative to publishing to a static URL, another possibility could be to use a Sonatype OSSHR account to publish the snapshot (with `mvn deploy`) to Maven Central, so it can be referenced easily.
> I even think it should actually be preferred.

Okay sounds good I will be looking into that. I'm currently testing out GitHub packages.
Also excuse the messy commit history that's currently going on...

**Comment by mickaelistria** [comment]
Don't bother too much at the moment. If you're having progress with GitHub packages, let's stick to them; maybe we'll switch to regular Maven later if need be.

**Comment by mickaelistria** [comment]
One issue is that the generated repo at https://github.com/AObuchow/lsp4xml-extensions-maven/packages/103857 seems to be totally confused because the `artifactId` contains dots, so it doesn't list a proper groupId and so on.
I think we should simplify the project groupId/artifactId so that the `artifactId` becomes a single-word. I suggest `maven-xmlls-extension`.

**Comment by AObuchow** [comment]
> One issue is that the generated repo at https://github.com/AObuchow/lsp4xml-extensions-maven/packages/103857 seems to be totally confused because the `artifactId` contains dots, so it doesn't list a proper groupId and so on.
> I think we should simplify the project groupId/artifactId so that the `artifactId` becomes a single-word. I suggest `maven-xmlls-extension`.

Good catch, I'll update the artifactId and the groupId (if necessary).

**Comment by mickaelistria** [comment]
Apparently, we cannot access the GitHub Maven packages repo publicly; we're kind of forced to enable GitHub authentication in settings.xml. I can do it locally but need to investigate how this can be enabled for m2e build...

**Comment by AObuchow** [comment]
> Apparently, we cannot access the GitHub Maven packages repo publicly; we're kind of forced to enable GitHub authentication in settings.xml. I can do it locally but need to investigate how this can be enabled for m2e build...

Are we able to issue a specific maven command for the m2e build?
We could potentially create a custom `settings.xml` and run maven using` mvn --settings customSettings.xml clean install`.

In the meantime, I'm going to investigate Sonatype OSSHR. Maybe GitHub packages isin't ready for our use case just yet (I also read there's limitations with regards to Maven snapshots).

**Comment by mickaelistria** [comment]
> Are we able to issue a specific maven command for the m2e build?

Better than that, we're admin on the build job so we can change the build job to add extra settings.
However, my question is more about what are the values to set. I've asked this on the cbi-dev list: https://www.eclipse.org/lists/cbi-dev/msg02206.html

**Comment by AObuchow** [comment]
Okay great, thanks for asking that on the mailing list.

**Comment by mickaelistria** [comment]
Seems like Eclipse Foundation staff can fix the missing GitHub credentials. I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=559195 with the request.

**Comment by mickaelistria** [comment]
This seems to work on m2e side. We can close it and use new more specific tickets for further issues.
Thanks Andrew, leveraging GitHub actions was a good choice, and it didn't take you long to have something ready!
