### ISSUE TITLE
Submodule diagnostics and completion should use working copy

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/lsp4xml-extensions-maven#16]
Currently, submodule diagnostics and completion use the pom file on disk rather than a working copy. Thus the contents might differ / get out of sync.

All areas in the codebase where the maven model is instantiated using the pom file on disk rather than the working copy should be updated to prevent future bugs. (Additionally, the maven model shouldn't be instantiated more than once. It should be passed around, but that's another bug).

**Comment by AObuchow** [comment]
Completion was updated to use MavenProjectCache in 4f72b5557ae65bd23ac2958e6d8ce7bd625258d9

**Comment by mickaelistria** [comment]
I think this is replaced by #68 so we can close it.
