### ISSUE TITLE
Dependency completion insertion bug

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/lsp4xml-extensions-maven#29]
If a dependency autocompletion is triggered on the same line as a `</dependency>` tag, the existing `</dependency>` will be overwritten, leading to invalid XML.

See [this demo for a visualization of the bug](https://photos.app.goo.gl/S1oCJ1MGLhUC2zuv7).

**Comment by mickaelistria** [comment]
Some recent change in completion (don't know which one-s- exactly) seem to have fixed that.
