### ISSUE TITLE
Completion for plugins (similar to completion for dependencies)

### ISSUE THREAD

**Issue by mickaelistria** [AObuchow/lsp4xml-extensions-maven#32]
Similarly to how completion for dependencies is implemented, the extension should support completion for plugins. As there is much to share here, both should try to be as factorized as possible so adding a feature for dependencies automatically adds it to plugins.

**Comment by AObuchow** [comment]
> As there is much to share here, both should try to be as factorized as possible so adding a feature for dependencies automatically adds it to plugins.

+1 this should be a priority to reduce duplicate development efforts.

**Comment by AObuchow** [comment]
I believe the only thing that needs to be modified to properly search for maven plugins is to set the `MAVEN.PACKAGING` to `"maven-plugin"` [when constructing an indexer query](https://github.com/AObuchow/lsp4xml-extensions-maven/blob/master/org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java#L134).

**Comment by mickaelistria** [comment]
This is now in.
