### ISSUE TITLE
Hover for existing <configuration> children element in plugin & plugin execution

### ISSUE THREAD

**Issue by mickaelistria** [AObuchow/lsp4xml-extensions-maven#40]
When hovering on a child of <configuration>, extension should show as much relevant information as possible for this element. This includes documentation, type, default value...

**Comment by AObuchow** [comment]
This was added in https://github.com/AObuchow/lsp4xml-extensions-maven/commit/fe7bf75f2d497b6a9f586f519f107cbd648cf919
