### ISSUE TITLE
Duplicate artifactId's in remote artifactId completion

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/lsp4xml-extensions-maven#54]
When doing completion for remote artifactId's, there are duplicate completion's:
![image](https://user-images.githubusercontent.com/10300119/75458252-8eb70600-594b-11ea-8f77-253155411877.png)
My guess is that two maven central indexes are being added to the list of remote repositories, which is something I had run into myself prior to https://github.com/AObuchow/lsp4xml-extensions-maven/commit/d5145310a5c5d152e34709b54161a1aad8c9af83. I had solved it by checking for duplicate remote repository Id's (but this solution could lead to other bugs).  Alternatively, we could filter for duplicate artifactId's (maybe prioritizing the artifactInfo that's getDescription() is non null).

**Comment by mickaelistria** [comment]
Does #57 help?

**Comment by AObuchow** [comment]
> Does #57 help?

To some extent, yes (see my comment on the PR).

For now, I've solved the issue by [removing the trailing `/` ](https://github.com/AObuchow/lsp4xml-extensions-maven/commit/af0ba643a8afd7c4ee4c49e01153335547cd9d23#diff-644fbb2cadadc069cea44da435e4633bR60)from the maven central repo URL.

The issue might arise again however. In this case it occured because we had 2 maven central repo instances, which only differed by a trailing `/`.

**Comment by AObuchow** [comment]
Closing for now as the issue was fixed with https://github.com/AObuchow/lsp4xml-extensions-maven/commit/af0ba643a8afd7c4ee4c49e01153335547cd9d23#diff-644fbb2cadadc069cea44da435e4633bR60
