### ISSUE TITLE
Migrate lsp4xml dependency to LemMinX

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/lsp4xml-extensions-maven#66]
Now that lsp4xml has migrated to https://github.com/eclipse/lemminx, we should be able to depend on LemMinX, allowing us to fix bugs such as https://github.com/AObuchow/lsp4xml-extensions-maven/issues/53.

**Comment by mickaelistria** [comment]
We need to wait for a first release of LemMinX and have this 1st release of LemMinX released into Wild Web Developer before changing this extension.

**Comment by AObuchow** [comment]
Done in 8c9955e24c0d05c72c8bcf820619ddb3c2f588ba
