### ISSUE TITLE
Fix plugin configuration description formatting

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/lsp4xml-extensions-maven#71]
The markdown for the plugin configuration hovers/completions uses `\n` when it should be using `\`.

**Comment by AObuchow** [comment]
`\` doesn't seem to work but `</br>` does.

**Comment by mickaelistria** [comment]
IIRC, the convention for markdown is to use 2 newlines ('\n\n`) to start a new paragraph.

**Comment by AObuchow** [comment]
> IIRC, the convention for markdown is to use 2 newlines ('\n\n`) to start a new paragraph.

Thanks, will try this out.
